const porpertyDetail= `{
  "bk_state_kbn": 2,
  "bk_sbt_kbn": 32,
  "sakimono_flg": 1,
  "kyakutsuke_pass_flg": "0",
  "bk_kakunin_date": "2022-07-16",
  "bk_item_kbn": 3202,
  "tate_kozo_kbn": 1,
  "shozai_kai_kbn": 1,
  "madori_kbn": 5,
  "bal_flg": 1,
  "koshinryo_flg": "0",
  "chinhoshokin_kbn": 1,
  "hoshonin_daiko_company_flg": 2,
  "hoken_flg": "1",
  "genkyo_kbn": 21,
  "hikiwatashi_kbn": 3,
  "parking_state_kbn": 1,
  "shinchiku_flg": "0",
  "torihiki_kbn": 5,
  "banchi": "30番14号",
  "setsubi_kbn_renketsu": [
    "1021",
    "1099",
    "1013",
    "1232",
    "1040",
    "1058",
    "1081",
    "1218",
    "1231",
    "1060",
    "1014",
    "1022",
    "1023",
    "1056",
    "1083",
    "1206",
    "1292",
    "1016",
    "1087",
    "1062",
    "1395",
    "1401",
    "1077",
    "1027",
    "1007",
    "1086",
    "1036",
    "2056",
    "2459",
    "2461",
    "2460",
    "1003",
    "1202",
    "1034",
    "1025"
  ],
  "walk_time_1": 13,
  "walk_time_2": 13,
  "walk_time_3": 15,
  "chiku_ymd": "2013-01-01",
  "keiyaku_years": 2,
  "hikiwatashi_ymd": "2022-08-01",
  "room_type_kbn_1": 5,
  "room_josu_1": 11.6,
  "room_shozaikai_1": 2,
  "room_shozaikai_kbn_1": 1,
  "room_type_kbn_2": 2,
  "room_josu_2": 6.0,
  "room_shozaikai_2": 2,
  "room_shozaikai_kbn_2": 1,
  "kyoekihi_kanrihi_flg": "1",
  "churinjo_umu_kbn": 4,
  "kyoekihi": 3000,
  "hikiwatashi_ymd_jun_kbn": 3,
  "teishaku_keiyaku_flg": "0",
  "running_price_1": 330,
  "running_name_1": "24時間サポート",
  "running_kbn_1": 1,
  "address_name": "東京都世田谷区代沢4丁目",
  "ensen_name_1": "小田急電鉄小田原線",
  "eki_name_1": "下北沢",
  "ensen_name_2": "京王電鉄井の頭線",
  "eki_name_2": "池ノ上",
  "ensen_name_3": "小田急電鉄小田原線",
  "eki_name_3": "世田谷代田",
  "room_no": "202",
  "tatemono_name": "ソレアード代沢",
  "tatesen_menseki": 41.56,
  "reikin": 1.0,
  "chijo_kai": 3,
  "shozai_kai": 2,
  "madori_room_su": 1,
  "price": 126000,
  "shikikin_flg": "0",
  "hoshokin_flg": "0",
  "reikin_flg": "1",
  "reikin_tani_kbn": 1,
  "yusen_kotsu_kbn_1": 1,
  "yusen_kotsu_kbn_2": 1,
  "yusen_kotsu_kbn_3": 1,
  "gaibu_bk_cd": "43e72436b85229d97775291349",
  "gyosha_name": "大東建託パートナーズ(株)　世田谷営業所",
  "gyosha_tel": "0354315630",
  "chinhosho_naiyo": "契約時保証委託料：22，000円 月額保証委託料：賃料総額の2.2％又は5.5％",
  "originalId": "RID20220716011735273246ID10843010027"
}`

const publishOrder = `{
  "churinjo_umu_kbn": "",
  "shinchiku_flg": "1",
  "bk_item_kbn": "3202",
  "teishaku_keiyaku_flg": "0",
  "bk_kakunin_date": "2022/07/16",
  "price": "126000.0",
  "reikin": "1",
  "reikin_flg": "1",
  "reikin_tani_kbn": "1",
  "kyoekihi_kanrihi_flg": "0",
  "kanrihi": "",
  "shikikin": "",
  "shikikin_flg": "0",
  "shikikin_tani_kbn": "None",
  "kyoekihi": "3,000",
  "hoshokin": "",
  "tatesen_menseki": "41.56",
  "parking_yuryo_flg": "0",
  "parking_state_kbn": "0",
  "tate_kozo_kbn": "None",
  "genkyo_kbn": "21",
  "keiyaku_years": "2年",
  "keiyaku_months": "",
  "chiku_ymd": "2013-01-01",
  "setsubi_kbn_renketsu": "Ｂ・Ｔ別 オートバス シャワー 追焚機能 浴室乾燥機 温水洗浄便座 シャワー付洗面化粧台 洗面所独立 ガスコンロ可 ３口以上コンロ システムキッチン グリル 浄水器 照明器具 室内洗濯機置場 給湯 都市ガス フローリング エアコン ＣＳ ＢＳ端子 モニタ付インターホン バルコニー",
  "bal_flg": "None",
  "address_name": "東京都世田谷区代沢４丁目",
  "banchi": "３０番１４号",
  "ensen_name_1": "小田急小田原線",
  "eki_name_1": "下北沢",
  "walk_time_1": "13分",
  "bus_time_1": "小田急小田原線 下北沢 徒歩13分",
  "bus_stop_name_1": "",
  "bus_stop_walk_time_1": "None",
  "yusen_kotsu_kbn_1": "小田急小田原線 下北沢 徒歩13分",
  "ensen_name_2": "京王井の頭線",
  "eki_name_2": "池ノ上",
  "walk_time_2": "13分",
  "bus_time_2": "京王井の頭線 池ノ上 徒歩13分",
  "bus_stop_name_2": "",
  "bus_stop_walk_time_2": "None",
  "yusen_kotsu_kbn_2": "京王井の頭線 池ノ上 徒歩13分",
  "ensen_name_3": "小田急小田原線",
  "eki_name_3": "世田谷代田",
  "walk_time_3": "15分",
  "bus_time_3": "小田急小田原線 世田谷代田 徒歩15分",
  "bus_stop_name_3": "",
  "bus_stop_walk_time_3": "None",
  "yusen_kotsu_kbn_3": "小田急小田原線 世田谷代田 徒歩15分",
  "zappi": "なし",
  "madori_room_su": "",
  "madori_kbn": "5",
  "chijo_kai": "3階建",
  "chika_kai": "",
  "shozai_kai": "3階建/2階部分",
  "shozai_kai_kbn": "1",
  "maisonette_kai_from_kbn": "None",
  "maisonette_kai_to_kbn": "None",
  "hikiwatashi_ymd": "2022-2022-1",
  "hikiwatashi_ymd_jun_kbn": "3",
  "hikiwatashi_kbn": "4",
  "koshinryo": "",
  "koshinryo_kbn": "None",
  "koshinryo_flg": "2",
  "hoken_flg": "0",
  "hoken_keiyaku_kikan": "",
  "hoken_kakekin": "",
  "gyosha_name": "大東建託パートナーズ(株)",
  "gyosha_tel": " 03-5431-5630",
  "tatemono_name": "ソレアード代沢",
  "room_no": "202"
}`



;(function compareJsonFile(json1, json2) {
  const porpertyDetailObj= JSON.parse(json1)
  const publishOrderObj= JSON.parse(json2)
  const keys = [...Object.keys(porpertyDetailObj)]

  //console.log('====== |key| -- |porpertyDetailObj| -- |publishOrderObj| ')

  for(let i = 0; i< keys.length ; i++){
    if(porpertyDetailObj[keys[i]]==publishOrderObj[keys[i]]){
      console.log( `<same> |${keys[i]}| :: |${porpertyDetailObj[keys[i]]}| -- |${publishOrderObj[keys[i]]}|` )
    }else{
      console.log( `<diff> |${keys[i]}| :: |${porpertyDetailObj[keys[i]]}| -- |${publishOrderObj[keys[i]]}|` )
    }
  }
})(porpertyDetail, publishOrder);
